packages:
  - packages/trace
  - packages/extension
  - packages/editor

allowBuilds:
  esbuild: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@cutscene/*'

onlyBuiltDependencies:
  - esbuild
