import type { BoundingBox, RecordingMeta, TargetDescriptor, TraceEvent } from './schema.ts';

// Step-by-step documentation generated from the trace. The action copy comes
// from the DOM's accessible name, never from a language model. One section per
// documented step; the editor renders the cropped screenshot each section
// references.

export type DocStep = {
  index: number;
  stepId: string;
  eventId: string;
  t: number;
  route: string;
  action: string;
  box: BoundingBox | null;
  screenshot: string | null;
};

const DOCUMENTED = new Set<TraceEvent['type']>(['navigation', 'interaction.click', 'interaction.input']);

// A masked field never leaks its accessible name into the doc; fall back to a
// structural label so the sentence stays truthful without exposing a secret.
export function targetLabel(target: TargetDescriptor): string {
  const accessibleName = target.accessibleName.trim();
  if (accessibleName && accessibleName !== '[MASKED]') return accessibleName;
  const text = target.text.trim();
  if (text && text !== '[MASKED]') return text;
  return target.role ?? target.tagName.toLowerCase();
}

function screenshotName(index: number): string {
  return `screenshots/step-${String(index).padStart(2, '0')}.png`;
}

function actionText(event: TraceEvent): string {
  if (event.type === 'navigation') return `Open \`${event.route}\`.`;
  const target = event.target;
  if (!target) return event.type === 'interaction.click' ? 'Click the target element.' : 'Enter a value.';
  const label = targetLabel(target);
  if (event.type === 'interaction.click') return `Click **${label}**.`;
  const value = target.value;
  return value && value !== '[MASKED]' ? `Enter \`${value}\` into **${label}**.` : `Fill in **${label}**.`;
}

export function deriveDocSteps(events: readonly TraceEvent[]): DocStep[] {
  const steps: DocStep[] = [];
  for (const event of events) {
    if (!DOCUMENTED.has(event.type)) continue;
    const index = steps.length + 1;
    const box = event.target?.boundingBox ?? null;
    steps.push({
      index, stepId: event.stepId, eventId: event.id, t: event.t, route: event.route,
      action: actionText(event), box, screenshot: box ? screenshotName(index) : null,
    });
  }
  return steps;
}

export function renderDocMarkdown(steps: readonly DocStep[], meta: Pick<RecordingMeta, 'recordingId' | 'url'>): string {
  const lines: string[] = [
    `# ${meta.recordingId}`,
    '',
    `Generated by Cutscene from a recording of \`${meta.url}\`.`,
    '',
  ];
  if (steps.length === 0) {
    lines.push('No documented steps were captured.', '');
    return lines.join('\n');
  }
  for (const step of steps) {
    lines.push(`## Step ${step.index}`, '', step.action, '');
    if (step.screenshot) lines.push(`![Step ${step.index}](${step.screenshot})`, '');
  }
  return lines.join('\n');
}
