import type { RecordingMeta, TargetDescriptor, TraceEvent } from './schema.ts';

// A skeleton, not a test. It replays the recorded flow by resolving each step's
// ranked locators in order; it never asserts. The recorder does not know intent,
// so every derived expectation is emitted as a `// suggested:` comment.

export type SkeletonInput = {
  meta: Pick<RecordingMeta, 'recordingId' | 'url'>;
  events: readonly TraceEvent[];
};

const ACTIONABLE = new Set<TraceEvent['type']>(['interaction.click', 'interaction.input']);

// Single-quoted string emission: a name carrying a quote or backslash must not
// break the generated source.
function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

// Highest-confidence locator first; the descriptor's list is already ranked
// descending by packages/trace/locators.
function accessor(target: TargetDescriptor): string | null {
  const locator = target.locators[0];
  if (!locator) return null;
  switch (locator.type) {
    case 'testId':
      return `page.getByTestId(${quote(locator.value)})`;
    case 'role':
      return `page.getByRole(${quote(locator.role)}, { name: ${quote(locator.name)} })`;
    case 'label':
      return `page.getByLabel(${quote(locator.value)})`;
    case 'text':
      return `page.getByText(${quote(locator.value)})`;
    case 'css':
      return `page.locator(${quote(locator.value)})`;
  }
}

function identityOf(target: TargetDescriptor): string {
  return `${target.role ?? ''}::${target.accessibleName}`;
}

export function generatePlaywrightSkeleton(input: SkeletonInput): string {
  const { meta } = input;
  const lines: string[] = [
    "import { test, expect } from '@playwright/test';",
    '',
    `// Generated by Cutscene from recording ${meta.recordingId}.`,
    '// This is a skeleton, not a test. Assertions are suggested as comments.',
    `test(${quote(meta.recordingId)}, async ({ page }) => {`,
    `  await page.goto(${quote(meta.url)});`,
  ];

  const actionable = input.events.filter((event) => ACTIONABLE.has(event.type));
  const seen = new Set<string>();
  let lastRoute: string | null = null;
  let body = 0;

  for (const event of actionable) {
    const target = event.target;
    // A route change is observed on the event that follows the action that
    // caused it, so the suggestion precedes the current step.
    if (lastRoute !== null && event.route !== lastRoute) {
      lines.push(`  // suggested: route changed to ${event.route}`);
      if (target && !seen.has(identityOf(target)) &&
          target.accessibleName && target.accessibleName !== '[MASKED]') {
        lines.push(`  // suggested: "${target.accessibleName}" became visible`);
      }
    }
    lastRoute = event.route;

    if (!target) {
      lines.push('  // TODO: no target captured for this step');
      body += 1;
      continue;
    }
    seen.add(identityOf(target));

    const resolved = accessor(target);
    if (!resolved) {
      // No fabricated selector: a step without a locator is left for the reader.
      lines.push(`  // TODO: no locator resolved for ${quote(target.accessibleName)}`);
      body += 1;
      continue;
    }

    if (event.type === 'interaction.click') {
      lines.push(`  await ${resolved}.click();`);
    } else {
      const value = target.value ?? '';
      lines.push(`  await ${resolved}.fill(${quote(value)});`);
      if (value === '[MASKED]') lines.push('  // value was masked at capture time');
    }
    body += 1;
  }

  if (body === 0) lines.push('  // no actionable events captured');
  lines.push('});', '');
  return lines.join('\n');
}
